services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-production}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"

  db:
    image: postgres:15-bullseye
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-decidimos}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-1234}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  bundle_cache:
  postgres_data:
