
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: decidim_app
      POSTGRES_PASSWORD: thepassword
      POSTGRES_DB: decidim_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - decidim-network

  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: decidim_app
      DATABASE_PASSWORD: thepassword
      DATABASE_URL: postgresql://decidim_app:thepassword@db:5432/decidim_app
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - decidim-network
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"

volumes:
  postgres_data:
  bundle_data:

networks:
  decidim-network:
    driver: bridge
